renv::snapshot()

library(tidyverse)
library(dplyr)
library(future)
library(furrr)
library(reticulate)
library(mlflow)
library(conflicted)

#source(".Rprofile")
source("model_scripts/analysis_scripts/run_analysis.R")
#source(".Rprofile")
source("model_scripts/analysis_scripts/run_analysis_nopred.R")

c("select", "filter") %>% walk(~ conflict_prefer(.x, "dplyr"))
c("year", "month") %>% walk(~ conflict_prefer(.x, "lubridate"))
c("map") %>% walk( ~ conflict_prefer(.x, "purrr"))
c("sd") %>%  walk(~ conflict_prefer(.x, "stats"))
c("match") %>%  walk(~ conflict_prefer(.x, "base"))

its_outcomes <- c("chicken_fish","meat","nonvegan","total","vegan","vegetarian")
targeted_its_outcomes <- c("breakfast","untextured","textured")
targeted_customer_outcomes <- c("breakfast","untextured")

targeted_its_restaurants <- list(breakfast = c('2HRX9P6HKXA8V','JHDN7CF1C03X5','L69HYJ4Y3TR91','ED5J990H5VAZT'),
                                 untextured = c('SRQS8F7JWA9MZ','JHDN7CF1C03X5'),
                                 textured = c('VLZX7K2M9QD4T'))
targeted_customer_restaurants <- list(breakfast = c('2HRX9P6HKXA8V','L69HYJ4Y3TR91','ED5J990H5VAZT'),
                                      untextured = c('SRQS8F7JWA9MZ'))

#run_its(outcome="nonvegan",directory="testing")
#run_its_fast(outcome="nonvegan",directory="fast")
#run_nolags_its(outcome="nonvegan", directory="testing_no_lags")
#run_fewlags_its(outcome="nonvegan", directory="testing_few_lags", adapt_delta=.85, max_treedepth=10)
#tmurun_regularized_its(outcome="nonvegan", directory="testing_regularized", adapt_delta=.85, max_treedepth=10)
#run_nopred_its(outcome="nonvegan")
#run_regularized2_its(outcome="nonvegan", directory="testing_regularized2", adapt_delta=.85, max_treedepth=10)
#run_notime_its(outcome="nonvegan", directory="testing4_notime", adapt_delta=.85, max_treedepth=10)
#run_1time_its(outcome="nonvegan", directory="testing4_1time", adapt_delta=.85, max_treedepth=10)
#run_2time_its(outcome="nonvegan", directory="testing4_2time", adapt_delta=.85, max_treedepth=10)
#run_3time_its(outcome="nonvegan", directory="testing4_3time", adapt_delta=.85, max_treedepth=10)
#run_4time_its(outcome="nonvegan", directory="testing4_4time", adapt_delta=.85, max_treedepth=10)
#run_5time_its(outcome="nonvegan", directory="testing4_5time", adapt_delta=.85, max_treedepth=10)
#run_6time_its(outcome="nonvegan", directory="testing4_6time", adapt_delta=.85, max_treedepth=10)
#run_regularized3_its(outcome="nonvegan", directory="testing_regularized3", adapt_delta=.85, max_treedepth=10)
#run_regularized4_its(outcome="nonvegan", directory="testing_regularized4", adapt_delta=.85, max_treedepth=10)
#run_regularized5_its(outcome="nonvegan", directory="testing_regularized5", adapt_delta=.85, max_treedepth=10)
#run_6time_its(outcome="nonvegan", directory="testing_lessclipped", adapt_delta=.85, max_treedepth=10)
#run_5time_its(outcome="nonvegan", directory="testing_lessclipped_noweekend", adapt_delta=.85, max_treedepth=10)
#run_regularized4_its(outcome="nonvegan", directory="testing_lessclipped_regularized4", adapt_delta=.85, max_treedepth=10)
#run_regularized4_noweekend_its(outcome="nonvegan", directory="testing_lessclipped_regularized4_noweekend", adapt_delta=.85, max_treedepth=10)
#run_regularized5_noweekend_its(outcome="nonvegan", directory="testing_lessclipped_regularized5_noweekend", adapt_delta=.85, max_treedepth=10)
#run_reglag_noregpred_its(outcome="nonvegan", directory="testing_lessclipped_reglag_noregpred", adapt_delta=.85, max_treedepth=10)
run_regpred_noreglag_its(outcome="nonvegan", directory="testing_lessclipped_regpred_noreglag", adapt_delta=.85, max_treedepth=10)