artifact_location: //home/nuttidalab/Documents/Jared/Other/testing/mlflow/764926900037454054
creation_time: 1754414421430
experiment_id: '764926900037454054'
last_update_time: 1754414421430
lifecycle_stage: active
name: Multilevel INGARCH Linear Transfer
